Add coloqio necessary resources and eks config files
Wealize/infra pull request #4
Opened 2020-12-02 12:45 UTC by anthares101

## Description

- Update coloqio resources files with the postgres database, backend ecr and Storageclass
- Add coloqio eks config

2020-12-09 10:21 UTC, javaguirre requested changes
Lo dicho, Fargate no soporta el plugin EBS de AWS, quizas tampoco otros, pero si no estamos pensando en usarlos, todo OK.

Yo empece usando Fargate pero pase a nodos EC2 por problemas con algun plugin, pero estaria bien volver a probar si no vamos a crear volumenes. :-)

2020-12-09 10:21 UTC, javaguirre commented on k8s/coloqio-eks.yaml
> +      - namespace: kube-system
Si queremos crear volumenes kube-system no puede estar en Fargate, es una limitacion de AWS, FYI.

2020-12-09 11:18 UTC, anthares101 commented on k8s/coloqio-eks.yaml
> +      - namespace: kube-system
En principio en front no hace falta y en back si creamos una base de datos en aws en vez de andar usando pods y tal no deberían hacer falta volumenes. Para review apps podemos no usar volumenes directamente y no persistir datos no se como lo ves

2020-12-10 09:24 UTC, javaguirre commented on k8s/coloqio-eks.yaml
> +      - namespace: kube-system
vale, probemos asi

2020-12-10 09:24 UTC, javaguirre approved these changes

2020-12-10 09:24 UTC, merged